# name: CI

# on:
#   # Triggers the workflow on pull request events but only for the "main" branch
#   pull_request:
#     branches: [ "main" ]

#   workflow_dispatch:

# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:13
#         env:
#           POSTGRES_DB: Traders
#           POSTGRES_USER: ammar
#           POSTGRES_PASSWORD: ammar
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd="pg_isready -U ammar"
#           --health-interval=10s
#           --health-timeout=5s
#           --health-retries=5

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout branch
#         uses: actions/checkout@v4
      
#       - name: Setup Python
#         uses: actions/setup-python@v5 
#         with:
#           python-version: '3.9' 

#       - name: Run a one-line script
#         run: echo Ready to build branch!

#       # Build branch using the runners shell
#       - name: Install dbt
#         run: pip3 install dbt-postgres

#       - name: Wait for Postgres
#         run: |
#           until pg_isready -h 127.0.0.1 -p 5432; do
#             echo "Waiting for Postgres...";
#             sleep 3;
#           done

#       - name: Deploy & Test Models (CI)
#         env:
#           DBT_USER: ammar
#           DBT_PASSWORD: ammar
#         run: dbt build --profiles-dir . --target dev